start:
	python3 src/manage.py runserver 8001

migration:
	python3 src/manage.py makemigrations

migrate:
	python3 src/manage.py migrate

freeze:
	pip freeze > requirements.txt

install:
	pip install -r requirements.txt

source:
	source .venv/bin/activate

assets:
	yarn start