# Generated by Django 4.0.2 on 2022-03-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Exchange',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Strategy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_imported', models.DateTimeField(blank=True, editable=False, null=True)),
                ('currency', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency', to='crypto.currency')),
                ('from_exchange', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crypto.exchange')),
                ('to_currency', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_currency', to='crypto.currency')),
            ],
            options={
                'verbose_name': 'Pair',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('backtest', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('exchange', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crypto.exchange')),
                ('pair', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crypto.pair')),
                ('strategy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crypto.strategy')),
            ],
            options={
                'verbose_name': 'Strategy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('timeframe', models.CharField(max_length=20)),
                ('open_datetime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('close_datetime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('open_amount', models.FloatField()),
                ('close_amount', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('volume', models.FloatField()),
                ('from_exchange', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.exchange')),
                ('pair', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.pair')),
            ],
            options={
                'verbose_name': 'Historic',
                'ordering': ['-created_at'],
            },
        ),
    ]
