# Generated by Django 4.0.2 on 2022-03-20 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order'},
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crypto.exchange'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crypto.pair'),
        ),
        migrations.AlterField(
            model_name='order',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crypto.strategy'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency', to='crypto.currency'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='from_exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crypto.exchange'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_currency', to='crypto.currency'),
        ),
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together={('from_exchange', 'currency', 'to_currency')},
        ),
    ]
