# Generated by Django 4.0.2 on 2022-03-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_order_options_alter_order_exchange_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historic',
            new_name='Historical',
        ),
        migrations.AlterModelOptions(
            name='historical',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historical'},
        ),
    ]
