# Generated by Django 4.0.2 on 2022-03-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_rename_pair_symbol_alter_symbol_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historical',
            unique_together={('from_exchange', 'symbol', 'timeframe', 'datetime')},
        ),
    ]
