# Generated by Django 4.0.2 on 2022-03-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_alter_historical_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='last_imported',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
