# Generated by Django 4.0.2 on 2022-03-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_exchange_slug_alter_symbol_last_imported'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='last_imported',
            new_name='last_imported_minute',
        ),
        migrations.AddField(
            model_name='symbol',
            name='last_imported_five_minutes',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='last_imported_fiveteen_minute',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='last_imported_four_hours',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='last_imported_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='last_imported_month',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='last_imported_week',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
