# Generated by Django 4.0.2 on 2022-03-23 00:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0007_rename_last_imported_symbol_last_imported_minute_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="symbol",
            old_name="last_imported_fiveteen_minute",
            new_name="last_imported_fiveteen_minutes",
        ),
        migrations.AlterUniqueTogether(
            name="symbol",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="symbol",
            name="from_currency",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="from_currency", to="crypto.currency"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="symbol",
            unique_together={("from_exchange", "from_currency", "to_currency")},
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="currency",
        ),
    ]
