# Generated by Django 4.0.2 on 2022-03-23 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_rename_last_imported_fiveteen_minute_symbol_last_imported_fiveteen_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='last_imported_month',
        ),
    ]
