# Generated by Django 4.0.2 on 2022-03-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_remove_symbol_last_imported_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='last_imported_twelve_hours',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
