# Generated by Django 4.0.2 on 2022-03-23 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_symbol_last_imported_twelve_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='symbol',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='from_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_currency', to='crypto.currency'),
            preserve_default=False,
        ),
    ]
