# Generated by Django 4.0.2 on 2022-03-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_alter_symbol_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='symbol',
            unique_together={('from_exchange', 'from_currency', 'to_currency')},
        ),
    ]
