# Generated by Django 4.0.2 on 2022-03-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0012_alter_symbol_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='last_imported_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
