# Generated by Django 4.0.2 on 2022-04-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0014_exchange_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='limit',
            field=models.CharField(default=1000, max_length=255),
            preserve_default=False,
        ),
    ]
