# Generated by Django 4.0.2 on 2022-04-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0016_symbol_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='max_per_second',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='limit',
            field=models.IntegerField(),
        ),
    ]
